---
- hosts: localhost
  tasks:
  - name: Create a host in Foreman
    foremanhost:
      name: foobar
      hostgroup: Medium/jenkins/blue
      compute_resource: libvirt
      state: present
      image: Jessie
      api_user: foreman
      api_password: changeme
      api_url: https://127.0.0.1
      ssl_verify: False
    register: result

  - debug:
      msg: Got "{{ result }}"

  - name: Shutdown a host in Foreman
    foremanhost:
      state: poweredOff
      name: foobar.example.com
    register: shutdow_result

  - assert:
      that:
        - shutdown_result.changed == false
        - shutdown_result.power_state == 'poweredOff'

  - name: Delete a host in Foreman
    foremanhost:
      name: foobar.example.com
      state: absent
      api_user: foreman
      api_password: changeme
      api_url: https://127.0.0.1
      ssl_verify: False
